### ISSUE TITLE
devcontainer using the wrong user

### ISSUE THREAD

**Issue by liamgreenlee** [HERMES-SOC/hermes_eea#6]
The devcontainer was updated in #3 but the extension configurations were not updated with new paths (they're currently set to use `/home/vscode`). The new user is also root, so new files are created as root and cannot be removed from the host.

**Comment by ehsteve** [comment]
Thank you for submitting this issue @liamgreenlee! We will look into it and hopefully have a fix soon.

**Comment by ehsteve** [comment]
@dbarrous this problem is likely true across all of the instrument packages.

**Comment by liamgreenlee** [comment]
I'm having a few problems with the updates you have here:
1. The default shell is `/bin/sh` not `/bin/bash`
2. Git does not work by default. `git config --global --add safe.directory /workspaces/hermes_eea` is required first.
3. Write permissions do not work on linux because the remote user does not inherit the uid/guid from the local user
